import 'package:flutter/material.dart';

class Complain {
  final String fullName;
  final String phoneNumber;
  final String emailAddress;
  final String description;
  final String ticketNumber;
  final int companyUnit;
  final bool resolved;

  Complain({
    @required this.fullName,
    @required this.phoneNumber,
    @required this.emailAddress,
    @required this.description,
    @required this.ticketNumber,
    @required this.companyUnit,
    this.resolved = false,
  });
}

List<Complain> complaints = [
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 1,
      resolved: true),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 2),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 3,
      resolved: true),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 4,
      resolved: true),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 5),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 1),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 2),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 3),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 4),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 5,
      resolved: true),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 1),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 1),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 1,
      resolved: true),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 2),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 4),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 5),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 2,
      resolved: true),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 1),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 3,
      resolved: true),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 4,
      resolved: true),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 1),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 5,
      resolved: true),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 3,
      resolved: true),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 1),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 1),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 3,
      resolved: true),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 4),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 1),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 5),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 2,
      resolved: true),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 1),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 2),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 1,
      resolved: true),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 4),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 1),
  Complain(
      fullName: 'John Doe',
      phoneNumber: '13498312212',
      emailAddress: 'johndoe@demo.com',
      description: 'Lorem Ipsum',
      ticketNumber: 'ticket-312',
      companyUnit: 4,
      resolved: true),
];
